### PR TITLE
Modified Work Experience list to make a bit more responsive

### PR DESCRIPTION
**Pull request by amanvishnani**
Please refer to the comment on the latest commit.

Thank You!

### CODE REVIEW

**Comment by amitmerchant1990** [comment]
@amanvishnani Hey can you please check why it is leaving so much space from top in the details?

**Comment by amanvishnani** [comment]
@amitmerchant1990 Hey I have removed that extra spaces please review!

**Comment by amitmerchant1990** [comment]
@amanvishnani don't you think giving just `margin-top:-70px;` and fixing the issue temporarily is really a bad idea? as this may cause some issues in future. Please if possible come up with an optimized solution that can help us in long run. Hope you get it. Thanks!

**Comment by amanvishnani** [comment]
@amitmerchant1990 `layout="column"` or `layout-xs="column"` automatically adds some margin above first `flex` element of `md-list-item`, the best I can think of right now is wrapping that style into a CSS class.

**Comment by amanvishnani** [comment]
@amitmerchant1990 I have made few changes plz check!

**Pull request closed without merging**
